# Generated by Django 4.2.2 on 2023-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblog',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
